 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/doctors", type: :request do
  # Doctor. As you add validations to Doctor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: 'Terawang' }
  }

  let(:invalid_attributes) {
    { name: '' }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Doctor.create! valid_attributes
      get admin_doctors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      doctor = Doctor.create! valid_attributes
      get admin_doctor_url(doctor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_doctor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      doctor = Doctor.create! valid_attributes
      get edit_admin_doctor_url(doctor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Doctor" do
        expect {
          post admin_doctors_url, params: { doctor: valid_attributes }
        }.to change(Doctor, :count).by(1)
      end

      it "redirects to the created doctor" do
        post admin_doctors_url, params: { doctor: valid_attributes }
        doctor = assigns(:doctor)
        expect(response).to redirect_to(admin_doctor_url(doctor))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Doctor" do
        expect {
          post admin_doctors_url, params: { doctor: invalid_attributes }
        }.to change(Doctor, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_doctors_url, params: { doctor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: 'Terawan' }
      }

      it "updates the requested doctor" do
        doctor = Doctor.create! valid_attributes
        patch admin_doctor_url(doctor), params: { doctor: new_attributes }
        doctor.reload
        expect(doctor.name).to eq new_attributes[:name]
      end

      it "redirects to the doctor" do
        doctor = Doctor.create! valid_attributes
        patch admin_doctor_url(doctor), params: { doctor: new_attributes }
        doctor.reload
        expect(response).to redirect_to(admin_doctor_url(doctor))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        doctor = Doctor.create! valid_attributes
        patch admin_doctor_url(doctor), params: { doctor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested doctor" do
      doctor = Doctor.create! valid_attributes
      expect {
        delete admin_doctor_url(doctor)
      }.to change(Doctor, :count).by(-1)
    end

    it "redirects to the doctors list" do
      doctor = Doctor.create! valid_attributes
      delete admin_doctor_url(doctor)
      expect(response).to redirect_to(admin_doctors_url)
    end
  end
end
