 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/hospitals", type: :request do
  # Hospital. As you add validations to Hospital, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: 'Siloam' }
  }

  let(:invalid_attributes) {
    { name: '' }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Hospital.create! valid_attributes
      get admin_hospitals_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      hospital = Hospital.create! valid_attributes
      get admin_hospital_url(hospital)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_hospital_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      hospital = Hospital.create! valid_attributes
      get edit_admin_hospital_url(hospital)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Hospital" do
        expect {
          post admin_hospitals_url, params: { hospital: valid_attributes }
        }.to change(Hospital, :count).by(1)
      end

      it "redirects to the created admin_hospital" do
        post admin_hospitals_url, params: { hospital: valid_attributes }
        hospital = assigns(:hospital)
        expect(response).to redirect_to(admin_hospital_url(hospital))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Hospital" do
        expect {
          post admin_hospitals_url, params: { hospital: invalid_attributes }
        }.to change(Hospital, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_hospitals_url, params: { hospital: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: 'Siloam Lippo Village' }
      }

      it "updates the requested admin_hospital" do
        hospital = Hospital.create! valid_attributes
        patch admin_hospital_url(hospital), params: { hospital: new_attributes }
        hospital.reload
        expect(hospital.name).to eq new_attributes[:name]
      end

      it "redirects to the admin_hospital" do
        hospital = Hospital.create! valid_attributes
        patch admin_hospital_url(hospital), params: { hospital: new_attributes }
        hospital.reload
        expect(response).to redirect_to(admin_hospital_url(hospital))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        hospital = Hospital.create! valid_attributes
        patch admin_hospital_url(hospital), params: { hospital: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested admin_hospital" do
      hospital = Hospital.create! valid_attributes
      expect {
        delete admin_hospital_url(hospital)
      }.to change(Hospital, :count).by(-1)
    end

    it "redirects to the admin_hospitals list" do
      hospital = Hospital.create! valid_attributes
      delete admin_hospital_url(hospital)
      expect(response).to redirect_to(admin_hospitals_url)
    end
  end
end
